server:
  port: 8001
spring:
  application:
    name: cloud-provider-paytment-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db2022
    username: root
    password: 123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mingyu.springcloud.domain

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/